### ISSUE TITLE
DAY11 作业中第三方库README文档网址分享

### ISSUE THREAD

**Issue by ljqbpm** [selfteaching/selfteaching-python-camp#1047]
在第三方库的本地文件夹里没有找到README文件，用help(yagmail)打印出来的文档也并不详细，最后在Github上找到了作业里的两个库的主页，页面首页有README文档：
>[requests: HTTP for Humans™](https://github.com/kennethreitz/requests)

>[yagmail -- Yet Another GMAIL/SMTP client](https://github.com/kootenpv/yagmail)

**Comment by xiaoguaishou01** [comment]
作业里面第三方库README文件也有给链接的噢
