### ISSUE TITLE
python interpreter

### ISSUE THREAD

**Issue by chengzhangcafe** [selfteaching/selfteaching-python-camp#1696]
在vscode配置python环境前，要确保python interpreter被包含在path environment variable里，这个怎么操作

**Comment by realcaiying** [comment]
你在哪看到的这段话，请附上原文内容

**Comment by chengzhangcafe** [comment]
On Windows, make sure the location of your Python interpreter (that is, the folder where it's installed, like c:\python32) is included in your PATH environment variable. You can check the location by running path at the command prompt. If the Python interpreter's folder isn't included, open Windows Settings, search for "environment", select Edit environment variables for your account, then edit the Path variable to include that folder.

**Comment by chengzhangcafe** [comment]
@realcaiying  这个是官方的指导原文

**Comment by chengzhangcafe** [comment]
On Windows, make sure the location of your Python interpreter (that is, the folder where it's installed, like c:\python32) is included in your PATH environment variable. You can check the location by running path at the command prompt. If the Python interpreter's folder isn't included, open Windows Settings, search for "environment", select Edit environment variables for your account, then edit the Path variable to include that folder.

**Comment by realcaiying** [comment]
看一下 issue #1835 把anaconda加到环境变量即可，python解释器就在里面
