### ISSUE TITLE
无法将公共作业仓库克隆到本地

### ISSUE THREAD

**Issue by chengzhangcafe** [selfteaching/selfteaching-python-camp#1831]
每天都打开gihub网页克隆公共仓库，每天都是止步1/3就报错。网速太慢，怎么解

**Comment by chengzhangcafe** [comment]
@realcaiying

**Comment by realcaiying** [comment]
请把报错的内容或者截图发出来一下

**Comment by chengzhangcafe** [comment]
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed

**Comment by chengzhangcafe** [comment]
@realcaiying  这是报错内容

**Comment by realcaiying** [comment]
在网上有一些解决方案你可以试试，不确定是否有效，因为我没有遇到过类似情况。

https://juejin.im/post/5a31e37df265da432f312221

**Comment by diaboius** [comment]
> 每天都打开gihub网页克隆公共仓库，每天都是止步1/3就报错。网速太慢，怎么解

第一步，你先compare across forks
第二步，在GitHub desktop fetch一下就好了，不需要每天克隆公库

**Comment by chengzhangcafe** [comment]
@realcaiying 您发的这些内容真心看不行 是不是还要学习git

**Comment by chengzhangcafe** [comment]
@realcaiying 您发的这些内容真心看不懂  是不是还要学习git

**Comment by chengzhangcafe** [comment]
@realcaiying  您发的这些内容真心看不懂 是不是还要学习git

**Comment by chengzhangcafe** [comment]
@diaboius  不是每天要克隆仓库 是克隆出现错误 你只能多试几次啊 看是网速还是别的问题
我已经fork了，下一步是克隆到本地

**Comment by chengzhangcafe** [comment]
有视频指导就好了 @realcaiying

**Comment by chengzhangcafe** [comment]
@realcaiying 您发的这些内容真心看不懂  是不是还要学习git

**Comment by chengzhangcafe** [comment]
@realcaiying   终于克隆成功了 用了手机4G热点
