### ISSUE TITLE
Day03 关于将自己的fork与原网站同步的问题

### ISSUE THREAD

**Issue by yangbisheng** [selfteaching/selfteaching-python-camp#1917]
出现了一个红色的new该怎么操作
<img width="1144" alt="screenshot" src="https://user-images.githubusercontent.com/49109198/55494684-d1a22800-566d-11e9-9491-1243e159abbf.png">

**Comment by shengzhulst** [comment]
你这个是已经是关闭的pull request 可以不用管的

**Comment by fangchengyue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
