### ISSUE TITLE
Day05 字典dict和元组tuple啥区别

### ISSUE THREAD

**Issue by pansij123** [selfteaching/selfteaching-python-camp#1983]
@yjz111

**Comment by yjz111** [comment]
字典使用键值对存储数据，通常存对象吧 可变类型 例如xiaoming = {
    "name": "小明",
    "age": 18,
    "height": 1.75}
元组 用于存储一串数据，不可变类型。tuple = (1,2,3)

**Comment by pansij123** [comment]
xiaoming = {
"name": ["小明","Ming Ming"],
"age": 18,
"height": 1.75}

OK?

**Comment by yjz111** [comment]
ok ! 字典的值 可以取任何数据类型，但 键 只能使用 字符串、数字或 元组。

**Comment by pansij123** [comment]
谢谢 这回明白了一些 其余的我自己试验一下
