### ISSUE TITLE
Day08 为什么要用异常？我知道他是干啥的 但不知道其应用场合

### ISSUE THREAD

**Issue by pansij123** [selfteaching/selfteaching-python-camp#2131]
@yjz111 

目前我感觉如果我想知道哪步可能异常 我就在那附近加一个 if else print 的组合，也能大概知道什么除了什么问题。

请有经验的人现身说法 谢谢

**Comment by yjz111** [comment]
等到后期做项目的时候会用到，比如爬虫爬取数据，写入文件或者数据库，中间可能会遇到很多问题，如果不加异常处理，代码可能只能运行一部分，若在一些可能会发生错误的代码处，加上异常处理，不影响后面代码的运行。try except finally 。举例子，写入文件出现错误，后面代码自然无法运行，文件无法关闭。。这时候可以加上异常处理解决
