### ISSUE TITLE
Day5 作业大写小转变中，代码出错

### ISSUE THREAD

**Issue by liuliang0910** [selfteaching/selfteaching-python-camp#2258]
`t1=text.replace('better', 'worse')   `
`t2=t1.split()  `
`t3=[]          `
`for a in t2:`
`	 if 'ea' not in a:`
`		t3.append(a)`
到一步，print（t3）是可以显示的，但是到下一步t4就进行不了
`t4=t3.swapcase()`
`print(t4)`
我的代码是这样的，显示是`t3`出错了，不知道哪位朋友可以指点一下

**Comment by liuliang0910** [comment]
@oneMoreTime1357 教练可以帮帮我吗

**Comment by yjz111** [comment]
代码缩进问题

**Comment by liuliang0910** [comment]
![Snip20190410_163](https://user-images.githubusercontent.com/26655952/55850500-26bace00-5b87-11e9-936f-d7d7f3dc760d.png)

**Comment by yjz111** [comment]
swapcase() 方法用于对字符串的大小写字母进行转换,你操作的是list

**Comment by liuliang0910** [comment]
> swapcase() 方法用于对字符串的大小写字母进行转换,你操作的是list

哦哦，请问可以怎么改好这个代码咧

**Comment by yjz111** [comment]
自己上网搜下python字符串和列表的转换，很简单自己试试，遇到问题再提问~

**Comment by liuliang0910** [comment]
> 自己上网搜下python字符串和列表的转换，很简单自己试试，遇到问题再提问~

好的，我弄好在发上来，谢谢大哥

**Comment by liuliang0910** [comment]
![Snip20190410_169](https://user-images.githubusercontent.com/26655952/55877715-5bea0f00-5bcd-11e9-88bb-925a8a7ba1fe.png)

谢谢你的指导，问题已解决 @yjz111

**Comment by yaodadada** [comment]
![捕获](https://user-images.githubusercontent.com/51871410/62419260-9ad92e80-b6ae-11e9-97d9-9fd3764f460a.PNG)
