### ISSUE TITLE
day7作业1.4，增加一个函数，调用其它两个函数输出合并结果，怎样解决？谢谢！

### ISSUE THREAD

**Issue by zhiguodavid** [selfteaching/selfteaching-python-camp#2604]
@srvz 没有头绪，教练帮忙指点，谢谢。

**Comment by srvz** [comment]
参考这个看一下 https://github.com/selfteaching/selfteaching-python-camp/pull/495/files#diff-53fda67fa6a70649cdb4cda6bca39264R97

**Comment by zhiguodavid** [comment]
收到，谢谢！
