### ISSUE TITLE
day3：commit总是不成功，之前没出现过这种情况。急求帮忙！

### ISSUE THREAD

**Issue by wendy88888** [selfteaching/selfteaching-python-camp#2649]
![commit failed](https://user-images.githubusercontent.com/49281271/56459093-74260f00-63c1-11e9-81c8-08031e00f809.jpg)

**Comment by nan1222** [comment]
参考链接：https://blog.csdn.net/shensiback/article/details/80256233

**Comment by wendy88888** [comment]
解决方法：https://blog.csdn.net/shensiback/article/details/80256233。
macos：点击菜单上github desktop    >     preferences  >   git   >  改成自己的name 和 email.
