### ISSUE TITLE
请教：怎样在下面的程序中添加过滤中文字符的指令，尝试数次都没有成功。

### ISSUE THREAD

**Issue by zhiguodavid** [selfteaching/selfteaching-python-camp#2705]
def stats_text_en(text):
    """1、使用字典（dict)统计text中每个英文单词出现的次数.
    2、添加类型检查，如果不是字符串类型为异常"""
    if type(text) == str:

        t1=text.replace(',',' ').replace('.','').replace('!','').replace('*',' ').replace('-','').replace('?','')#将文档中的标点符号用空格代替
        
        t2 = t1.split()
        #t3 = judge_pure_english(t2)
        from collections import Counter
        print (Counter(t2).most_common(100))
      
    else:
        if type(text) != str: #如果不是字符串类型就抛出异常
                raise ValueError ("This is not an str type")
   
text= '''Beautiful is better 中国 than ugly. Explicit is better than implicit. Simple is better than complex. Complex'''
#print(stats_text_en(text))

@Lbinyang

**Comment by yjz111** [comment]
使用正则  re.findall(u'[\u4e00-\u9fff]+', text)

**Comment by zhiguodavid** [comment]
好的，我再试试，谢谢！

**Comment by zhiguodavid** [comment]
请教这样使用对吗？感谢！@yjz111
        t2 = t1.split()
        t3 = re.findall(u'[\u4e00-\u9fff]+', t2)        
        #from collections import Counter
        #t4 = Counter(t3).most_common(100)
        #return t4
        print (t3)

**Comment by Lbinyang** [comment]
```python
def stats_text_cn(text,count=None):
    if type(text) == str : 
            text = re.findall(u'[\u4e00-\u9fff]+', text.strip())
            text = "".join(text)
            text = jieba.lcut(text,cut_all=False) 
            text1 = []
            for i in text:
                if len(i) >= 2:
                    text1.append(i)    
            return collections.Counter(text1).most_common(count)
    else:
        raise ValueError ('仅接受字符串类型参数，输入的不是字符串，请重新输入：')```
