### ISSUE TITLE
VS CODE 报错 command 'python.setInterpreter' not found 

### ISSUE THREAD

**Issue by xiaobo12311** [selfteaching/selfteaching-python-camp#2738]
之前都很好，正在编写DAY5作业第二项，突然发现程序没办法运行。重新选择环境，VS提示command 'python.setInterpreter' not found.

![image](https://user-images.githubusercontent.com/48748320/56639582-965eac00-66a3-11e9-9e99-07fb3b953230.png)

**Comment by srvz** [comment]
卸载 vs code python 扩展
下载这个 https://github.com/Microsoft/vscode-python/releases/download/2019.3.6558/ms-python-release.vsix 手动安装，顺便关掉扩展自动更新

**Comment by xiaobo12311** [comment]
> 卸载 vs code python 扩展
> 下载这个 https://github.com/Microsoft/vscode-python/releases/download/2019.3.6558/ms-python-release.vsix 手动安装，顺便关掉扩展自动更新

还是不行，卸载重新安装也不行...

**Comment by xiaobo12311** [comment]
> 卸载 vs code 里面安装的 Python 扩展，不是卸载 vs code。点击 Uninstall / 卸载
> <img alt="Screen Shot 2019-04-24 at 16 50 53" width="868" src="https://user-images.githubusercontent.com/2470962/56645966-3b33b600-66b1-11e9-98e7-97650d31960e.png">
> 
> 下载这个扩展包 https://github.com/Microsoft/vscode-python/releases/download/2019.3.6558/ms-python-release.vsix ，选择 Install From VISX， 找到扩展包下载的位置，手动安装扩展，然后选择 Disable Auto Update Extensions / 关闭自动更新扩展。
> <img alt="Screen Shot 2019-04-24 at 16 46 08" width="662" src="https://user-images.githubusercontent.com/2470962/56646016-4c7cc280-66b1-11e9-9442-e3388adc16f3.png">

实在抱歉，可能还要麻烦您。我的界面是这样的。
![image](https://user-images.githubusercontent.com/48748320/56649567-f6f7e400-66b7-11e9-85bb-61824cd0ea2f.png)
![image](https://user-images.githubusercontent.com/48748320/56649648-1abb2a00-66b8-11e9-96f5-2562fb082b59.png)

**Comment by xiaobo12311** [comment]
> 卸载 vs code 里面安装的 Python 扩展，不是卸载 vs code。点击 Uninstall / 卸载
> <img alt="Screen Shot 2019-04-24 at 16 50 53" width="868" src="https://user-images.githubusercontent.com/2470962/56645966-3b33b600-66b1-11e9-98e7-97650d31960e.png">
> 
> 下载这个扩展包 https://github.com/Microsoft/vscode-python/releases/download/2019.3.6558/ms-python-release.vsix ，选择 Install From VISX， 找到扩展包下载的位置，手动安装扩展，然后选择 Disable Auto Update Extensions / 关闭自动更新扩展。
> <img alt="Screen Shot 2019-04-24 at 16 46 08" width="662" src="https://user-images.githubusercontent.com/2470962/56646016-4c7cc280-66b1-11e9-9442-e3388adc16f3.png">

已经处理好了，非常感谢

**Comment by Jungle002** [comment]
![image](https://user-images.githubusercontent.com/48565809/57973334-10036480-79da-11e9-94e5-4a41bef97aa5.png)
这个是什么意思呢？但是又不影响程序运行。
