### ISSUE TITLE
求助：VS Code重新安装后终端运行出现一群信息提示，请牛人帮忙！

### ISSUE THREAD

**Issue by zhiguodavid** [selfteaching/selfteaching-python-camp#2755]
![image](https://user-images.githubusercontent.com/49134591/56703751-df167380-673c-11e9-9483-ea00301f80d2.png)
![image](https://user-images.githubusercontent.com/49134591/56703779-fb1a1500-673c-11e9-9d19-946946bb27c0.png)

**Comment by zhiguodavid** [comment]
@srvz @Lbinyang 请教练帮忙看看，谢谢！

**Comment by srvz** [comment]
你没有运行 pip install pyquery  吧？

**Comment by zhiguodavid** [comment]
重新安装Anaconda 勾选添加环境变量之后正常了，感谢教练们的耐心指导！
