### ISSUE TITLE
无法将变更推送到账户下的作业仓库

### ISSUE THREAD

**Issue by nolitaann** [selfteaching/selfteaching-python-camp#2902]
在本地仓库作业变更后提交了commit，然后push那步时不成功是怎么回事啊
![2](https://user-images.githubusercontent.com/48619862/56980449-fb883500-6bae-11e9-8481-d8c1f9731b12.png)

**Comment by nolitaann** [comment]
![3](https://user-images.githubusercontent.com/48619862/56980505-1eb2e480-6baf-11e9-92fd-17bfc120473f.png)

**Comment by srvz** [comment]
你是不是推送到主作业仓库去了？再检查一下你是不是 clone 你自己账户名下 fork 的作业仓库

**Comment by nolitaann** [comment]
> 你是不是推送到主作业仓库去了？再检查一下你是不是 clone 你自己账户名下 fork 的作业仓库

是的呢，我重新克隆仓库就好啦，谢谢
