### ISSUE TITLE
Day4 关于换行的提问

### ISSUE THREAD

**Issue by Evolvingwufan** [selfteaching/selfteaching-python-camp#3402]
前后对比两个代码，只是在第5行加入了Print()为什么就起到了换行的作用？
![九九乘法表未换行](https://user-images.githubusercontent.com/49020116/58066576-7a73fa80-7bbc-11e9-91de-1f74ec21d33e.jpg)

刚开始自己做的时候，不会换行。看到有大神解答说要加一个print()就可以换行，照做后发现正确。只是不知道原理是什么？
![九九乘法表换行](https://user-images.githubusercontent.com/49020116/58066619-abecc600-7bbc-11e9-9579-6ccda51c4747.jpg)

**Comment by Evolvingwufan** [comment]
@EthanYan6  请教练抽空帮忙解答

**Comment by EthanYan6** [comment]
print底层就实现了换行的功能

**Comment by seven-tears** [comment]
print（）可以让里面的循环每循环一次都强制换行，开始下一行的输出

**Comment by Evolvingwufan** [comment]
> 
> 
> print（）可以让里面的循环每循环一次都强制换行，开始下一行的输出

**Comment by Evolvingwufan** [comment]
> 
> 
> print（）可以让里面的循环每循环一次都强制换行，开始下一行的输出

了解了，谢谢解答

**Comment by Evolvingwufan** [comment]
> 
> 
> print底层就实现了换行的功能

之前以为print只有显示的功能，现在了解到还有换行的功能
