### ISSUE TITLE
DAY3 计算器这样实现，不知道有没有问题？

### ISSUE THREAD

**Issue by shaoguos** [selfteaching/selfteaching-python-camp#4273]
<img width="541" alt="屏幕快照 2019-07-03 22 44 57" src="https://user-images.githubusercontent.com/21104355/60601718-2415f080-9de5-11e9-806e-f8d3fbfd00cf.png">

**Comment by zhangchaoxian** [comment]
我觉得 没有问题
接着试试打印Hello World

**Comment by shaoguos** [comment]
嗯，这种方式可以实现混合运算，支持小括号。
