### ISSUE TITLE
Day2 -- Relatives

### ISSUE THREAD

**Issue by MayJiao0** [selfteaching/selfteaching-python-camp#5501]

**Comment by liujiayi0042** [comment]
@MayJiao0 你好学员，打卡区是 https://github.com/selfteaching-learning-notes/selfteaching-learning-notes.github.io/ 这个仓库

**Comment by MayJiao0** [comment]
> @MayJiao0 你好学员，打卡区是 https://github.com/selfteaching-learning-notes/selfteaching-learning-notes.github.io/ 这个仓库

请问可以删除吗？
