### ISSUE TITLE
【1901070018】14天学习记录与总结

### ISSUE THREAD

**Issue by yangbisheng** [selfteaching/selfteaching-python-camp#5604]
**14天打卡记录**

> 学号：1901070018
姓名：杨必胜
用时：4
总结：英语阅读还有点吃力，把资料全都看完了。
学号：1901070018
姓名：杨必胜
感受：第二次做难度降低，阅读英文还是有点难
1901070018
day3
用时3
总结：解决一个问题，不是很清楚原理
姓名：杨必胜
学号1901070018
学习内容：流程控制
学习时间：半个小时
总结：
之前反复阅读了自学是门手艺若干遍，现在再看今天的作业感觉很简单，会了都不难，觉得困难只是幻觉。
Day5
姓名：杨必胜
学号：1901070018
用时：2
总结：
由于反复阅读自学是门手艺，今天只遇到一个问题，花了了很多时间，没有解决。果断找第二种方法，这个问题记录下来，等以后基础足够在来研究
DAY6
姓名：杨必胜
学号：1901070018
用时：2
总结：
第二次做作业，和第一次做这个作业感觉完全不同，果然要重复足够多的次数。还有就是把注意力集中在解决问题上
DAY7
姓名：杨必胜
学号：1901070018
用时：2
总结：
由于反复阅读了自学是门手艺，还有查阅了一些教程，解决了模块找不到的问题。过程中提醒自己，没啥可怕的。
DAY8
姓名：杨必胜
学号：1901070018
用时：3
总结：
阅读了一遍文档，看懂了一部分就写出来了。虽然只是最基础的try…except
raise,但是读懂文档并且学会一个全新的一句。这对我来说是一个很大的进步
DAY9
姓名：杨必胜
学号：1901070018
用时：4
总结
阅读官方文档还是有些不懂，不过没有全部弄懂也没关系，因为懂最重要的就够用了。这次的内容和自学是门手艺中的一章相关。现在发现第一次进入训练营时竟然没有阅读这本书，在没有基础的情况下，一上来就看官方文档还是英文上结果可想而知。
DAY10
姓名你：杨必胜
学号；1901070018
用时；4
总结：
遇到环境变量的问题。因为下载了anaconda和pycharm 所以有两个python在电脑里。结果就是第三方库被下载到anaconda中，而pycharm环境中没有，最后用的Google找到了解决方法。
DAY11
姓名：杨必胜
学号：1901070018
用时：4
总结
这次的内容，官方文档不是很懂，还需要多看，基本上都是Google。我现在深刻理解了Google对于自学者的重要性。文档还需要反复阅读。
DAY12
姓名：杨必胜
学号：1901070018
学时：2
总结：
从开始接收到任务，一直到做完用了6天。其实做的时间只有两个小时，其它时间总是被困难幻觉所干扰。以后遇到困难幻觉，立刻开始行动。
DAY13
姓名：杨必胜
学号：1901070018
总结：
这次作业遇到了一些问题，在教练的帮助下通过反复阅读搜索解决了。通过这些天的学习，感觉自己理解了困难幻觉这个词。在自学的道路上所有的困难都是幻觉，懂了以后感觉不过如此，用就行了。
DAY14
姓名：杨必胜
学号：1901070018
总结：
入门结束了，自学还要继续。

**14天学习总结**
现在回过头来总结自学营的学习过程，真的不难的课程我从四月开始学总计用时141天。我之前总觉得接触python没多久，好像就两个月左右，github上的记录赤裸裸的粉碎了这个幻觉。 这141天中真正用在学习上的时间肯定没有14天，分别在day2、day2、day11(我上了两次训练营！)放弃了117天、9天、4天总计130天，真正学习的时间是10天（github真是个好东西），其中有几天每天都可以完成两天的作业。放弃的原因只有一个，太难了。
 尽管《自学是门手艺》中反复强调这些困难都是幻觉，尽管书中做了大量的心理建设，尽管这141天中我也断断续续地在读这本书，尽管每次放弃的时候都知道不应该放弃，但我还是放弃了。然后过一段时间又挣扎着开始。
 现在反思那些把我难住的知识点，其实就那么回事，真的不难。当时觉得难是因为阅读的量和次数都不够，当然就不会，然后就焦虑，然后就放弃了。 现在我深刻的理解了困难幻觉这个概念，所有的困难都是幻觉，等学会了就会发现就那么回事。 总结一下学习过程就一句话，没啥可怕的！

**Comment by yangbisheng** [comment]
@XINGRUFANG

**Comment by XINGRUFANG** [comment]
> @XINGRUFANG

已经收录到博客网站

**Comment by XINGRUFANG** [comment]
收录到了博客网站
