### ISSUE TITLE
Day01 如何查看自己教练的 Github 账户名

### ISSUE THREAD

**Issue by yingca1** [selfteaching/selfteaching-python-camp#68]
作业仓库根目录为班级目录。

每个班级目录下，都有一个 `README.md` 文件，该文件中会有各个班级教练的 Github 用户名。

**Comment by fangchengyue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
