### ISSUE TITLE
Day01 如何在 macOS 下创建文本文件和文件夹

### ISSUE THREAD

**Issue by yingca1** [selfteaching/selfteaching-python-camp#71]
## 创建文件夹
1. 如果您想要在桌面上创建文件夹，请点按桌面；否则，打开 Finder 窗口并浏览到要创建文件夹的位置。

2. 选取“文件”>“新建文件夹”，或按下 Shift-Command-N。
> 如果“新建文件夹”命令呈灰色，则无法在当前位置创建文件夹。例如，您无法在 Finder 边栏的“我的所有文件”部分中创建文件夹。

3. 输入文件夹的名称，然后按下 Return 键。

[macOS Sierra: 以文件夹形式整理文件](https://support.apple.com/kb/PH25633?viewlocale=zh_CN&locale=zh_CN)

## 创建文本文件
1. 打开 文本编辑 （TextEdit.app），进入编辑界面后

2. 同时按住 `Command + Shift + T` 组合建，编辑界面会发生改变

3. 然后保存文件，就可以获得文本文件了（默认 utf8 编码格式）

**Comment by oneMoreTime1357** [comment]
或者在想创建文件的地方打开terminal，然后在terminal中输入 touch xxx.txt 就创建好了
terminal如何打开？
右键点击文件夹任意一个文件，在'服务'选项中有一个在此文件夹打开terminal
