### ISSUE TITLE
Day01 自学营第一天学员问题整理汇总

### ISSUE THREAD

**Issue by yingca1** [selfteaching/selfteaching-python-camp#81]
### 目录
1. 安装 SourceTree 软件遇到的问题 https://github.com/selfteaching/selfteaching-python-camp/issues/81#issuecomment-474204082
2. macOS 不知道如何创建文本文件 https://github.com/selfteaching/selfteaching-python-camp/issues/81#issuecomment-474204570
3. 不知道如何查看自己教练的 Github 账户名 https://github.com/selfteaching/selfteaching-python-camp/issues/81#issuecomment-474204966
4. 不理解 在本地仓库创建新文件 这句话什么意思 https://github.com/selfteaching/selfteaching-python-camp/issues/81#issuecomment-474205484
5. Github 远程仓库和 Sourcetree 中的本地仓库分支不同步 https://github.com/selfteaching/selfteaching-python-camp/issues/81#issuecomment-474207903

**Comment by realcaiying** [comment]
# 安装 SourceTree 软件遇到的问题

1. 由于 SourceTree 需要链接 Bitbucket 账户才能使用，所以最好提前先注册一个 Bitbucket 账户。
> 由于是国外的服务商，所以部分地区网络可能会有些问题

相关问题：
1. 安装SourceTree软件过程中的小问题 https://github.com/selfteaching/selfteaching-python-camp/issues/6

**Comment by realcaiying** [comment]
# macOS 不知道如何创建文本文件

作业中有要求在本地创建一个 txt 文件，并写入内容。macOS 创建文本文件对新人来说不是很容易。

解决方案：请参考 #71

**Comment by realcaiying** [comment]
# 不知道如何查看自己教练的 Github 账户名

解决方案：亲参考 #68

**Comment by realcaiying** [comment]
# 不理解 `在本地仓库创建新文件` 这句话什么意思

这句话的意思是：在自己的本地电脑，找到仓库在文件管理器的位置，在`文件管理器`中正确的文件夹下面创建一个文件

SourceTree 和 Github Desktop 仅是管理操作 Git 的可视化界面，所有文件的操作可以通过操作系统的文件管理器操作，或者通过编写程序的 IDE 来创建编辑文件。

所以 SourceTree 和 Github Desktop 里确实没有创建文件的地方。

**Comment by realcaiying** [comment]
# Github 远程仓库和 Sourcetree 中的本地仓库分支不同步

Git 的机制中，远程仓库 和 本地仓库 同步是需要执行一些操作的。原理通过 Git 命令来解释如下：
> git remote update && git fetch

解决方案：请参考 #7 

相关的问题：
1. Github 远程仓库和 Sourcetree 中的本地仓库分支不同步的问题 #7
