### ISSUE TITLE
DAY2 对SourceTree、JupyterLab和Visual Studio Code之间关系的理解

### ISSUE THREAD

**Issue by baishanheishui** [selfteaching/selfteaching-python-camp#85]
刚开始用这几个工具，也是一头雾水，经过这两天的学习，以我个人的理解，总结了这3个工具之间的关系。
    SourceTree把Github远程账户上的文件克隆到本地计算机，在本地编写修改文件，而后，SourceTree可以将修改过的文件提交推送到Github远程账户上。
    JupyterLab便于阅读下载到本地的文件，如有修改的话，同样使用SourceTree将修改过的文件提交推送到Github远程账户上。
    Visual Studio Code适合编写调试代码，同样，代码文件修改后，同样可以使用SourceTree将修改过的代码文件提交推送到Github远程账户上。

**Comment by realcaiying** [comment]
duplicate to #88
